-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_12_10_5_3_0_ap_ufixed_9_7_5_3_0_ReLU_config11_s is
port (
    ap_ready : OUT STD_LOGIC;
    layer8_out_0_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_1_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_2_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_3_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_4_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_8_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_12_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_15_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_18_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_21_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_24_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_28_val : IN STD_LOGIC_VECTOR (11 downto 0);
    layer8_out_31_val : IN STD_LOGIC_VECTOR (11 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_12_10_5_3_0_ap_ufixed_9_7_5_3_0_ReLU_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_126_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_29_fu_138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_29_fu_144_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_30_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_30_fu_162_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_31_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_31_fu_180_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_32_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_32_fu_198_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_33_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_33_fu_216_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_34_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_34_fu_234_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_35_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_35_fu_252_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_36_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_36_fu_270_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_37_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_37_fu_288_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_38_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_38_fu_306_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_39_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_39_fu_324_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_40_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_40_fu_342_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_fu_130_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_29_fu_148_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_30_fu_166_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_31_fu_184_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_32_fu_202_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_33_fu_220_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_34_fu_238_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_35_fu_256_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_36_fu_274_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_37_fu_292_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_38_fu_310_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_39_fu_328_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_40_fu_346_p3 : STD_LOGIC_VECTOR (8 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_130_p3;
    ap_return_1 <= select_ln45_29_fu_148_p3;
    ap_return_10 <= select_ln45_38_fu_310_p3;
    ap_return_11 <= select_ln45_39_fu_328_p3;
    ap_return_12 <= select_ln45_40_fu_346_p3;
    ap_return_2 <= select_ln45_30_fu_166_p3;
    ap_return_3 <= select_ln45_31_fu_184_p3;
    ap_return_4 <= select_ln45_32_fu_202_p3;
    ap_return_5 <= select_ln45_33_fu_220_p3;
    ap_return_6 <= select_ln45_34_fu_238_p3;
    ap_return_7 <= select_ln45_35_fu_256_p3;
    ap_return_8 <= select_ln45_36_fu_274_p3;
    ap_return_9 <= select_ln45_37_fu_292_p3;
    icmp_ln45_29_fu_138_p2 <= "1" when (signed(layer8_out_1_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_30_fu_156_p2 <= "1" when (signed(layer8_out_2_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_31_fu_174_p2 <= "1" when (signed(layer8_out_3_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_32_fu_192_p2 <= "1" when (signed(layer8_out_4_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_33_fu_210_p2 <= "1" when (signed(layer8_out_8_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_34_fu_228_p2 <= "1" when (signed(layer8_out_12_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_35_fu_246_p2 <= "1" when (signed(layer8_out_15_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_36_fu_264_p2 <= "1" when (signed(layer8_out_18_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_37_fu_282_p2 <= "1" when (signed(layer8_out_21_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_38_fu_300_p2 <= "1" when (signed(layer8_out_24_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_39_fu_318_p2 <= "1" when (signed(layer8_out_28_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_40_fu_336_p2 <= "1" when (signed(layer8_out_31_val) > signed(ap_const_lv12_0)) else "0";
    icmp_ln45_fu_120_p2 <= "1" when (signed(layer8_out_0_val) > signed(ap_const_lv12_0)) else "0";
    select_ln45_29_fu_148_p3 <= 
        trunc_ln46_29_fu_144_p1 when (icmp_ln45_29_fu_138_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_30_fu_166_p3 <= 
        trunc_ln46_30_fu_162_p1 when (icmp_ln45_30_fu_156_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_31_fu_184_p3 <= 
        trunc_ln46_31_fu_180_p1 when (icmp_ln45_31_fu_174_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_32_fu_202_p3 <= 
        trunc_ln46_32_fu_198_p1 when (icmp_ln45_32_fu_192_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_33_fu_220_p3 <= 
        trunc_ln46_33_fu_216_p1 when (icmp_ln45_33_fu_210_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_34_fu_238_p3 <= 
        trunc_ln46_34_fu_234_p1 when (icmp_ln45_34_fu_228_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_35_fu_256_p3 <= 
        trunc_ln46_35_fu_252_p1 when (icmp_ln45_35_fu_246_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_36_fu_274_p3 <= 
        trunc_ln46_36_fu_270_p1 when (icmp_ln45_36_fu_264_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_37_fu_292_p3 <= 
        trunc_ln46_37_fu_288_p1 when (icmp_ln45_37_fu_282_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_38_fu_310_p3 <= 
        trunc_ln46_38_fu_306_p1 when (icmp_ln45_38_fu_300_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_39_fu_328_p3 <= 
        trunc_ln46_39_fu_324_p1 when (icmp_ln45_39_fu_318_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_40_fu_346_p3 <= 
        trunc_ln46_40_fu_342_p1 when (icmp_ln45_40_fu_336_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_fu_130_p3 <= 
        trunc_ln46_fu_126_p1 when (icmp_ln45_fu_120_p2(0) = '1') else 
        ap_const_lv9_0;
    trunc_ln46_29_fu_144_p1 <= layer8_out_1_val(9 - 1 downto 0);
    trunc_ln46_30_fu_162_p1 <= layer8_out_2_val(9 - 1 downto 0);
    trunc_ln46_31_fu_180_p1 <= layer8_out_3_val(9 - 1 downto 0);
    trunc_ln46_32_fu_198_p1 <= layer8_out_4_val(9 - 1 downto 0);
    trunc_ln46_33_fu_216_p1 <= layer8_out_8_val(9 - 1 downto 0);
    trunc_ln46_34_fu_234_p1 <= layer8_out_12_val(9 - 1 downto 0);
    trunc_ln46_35_fu_252_p1 <= layer8_out_15_val(9 - 1 downto 0);
    trunc_ln46_36_fu_270_p1 <= layer8_out_18_val(9 - 1 downto 0);
    trunc_ln46_37_fu_288_p1 <= layer8_out_21_val(9 - 1 downto 0);
    trunc_ln46_38_fu_306_p1 <= layer8_out_24_val(9 - 1 downto 0);
    trunc_ln46_39_fu_324_p1 <= layer8_out_28_val(9 - 1 downto 0);
    trunc_ln46_40_fu_342_p1 <= layer8_out_31_val(9 - 1 downto 0);
    trunc_ln46_fu_126_p1 <= layer8_out_0_val(9 - 1 downto 0);
end behav;
