set prj_name conifer_jettag
set part xc7z020clg400-1
set board_part digilentinc.com:pynq-z1:part0:1.0
set processing_system_ip xilinx.com:ip:processing_system7:5.5
set processing_system processing_system7
set ps_s_axi_port S_AXI_HP0
set ps_m_axi_port M_AXI_GP0
set top conifer_jettag_accelerator
set ip_name conifer_conifer_jettag
set version 1.5
