// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conifer_jettag_accelerator_decision_function_112 (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] p_read1;
input  [17:0] p_read2;
input  [17:0] p_read3;
input  [17:0] p_read4;
input  [17:0] p_read5;
input  [17:0] p_read6;
input  [17:0] p_read7;
input  [17:0] p_read8;
input  [17:0] p_read9;
input  [17:0] p_read10;
input  [17:0] p_read11;
output  [11:0] ap_return;
input   ap_ce;

wire   [0:0] icmp_ln86_fu_324_p2;
reg   [0:0] icmp_ln86_reg_1322;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln86_reg_1322_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1810_fu_330_p2;
reg   [0:0] icmp_ln86_1810_reg_1328;
reg   [0:0] icmp_ln86_1810_reg_1328_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1811_fu_336_p2;
reg   [0:0] icmp_ln86_1811_reg_1339;
reg   [0:0] icmp_ln86_1811_reg_1339_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1812_fu_342_p2;
reg   [0:0] icmp_ln86_1812_reg_1345;
wire   [0:0] icmp_ln86_1813_fu_348_p2;
reg   [0:0] icmp_ln86_1813_reg_1350;
reg   [0:0] icmp_ln86_1813_reg_1350_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1814_fu_354_p2;
reg   [0:0] icmp_ln86_1814_reg_1356;
reg   [0:0] icmp_ln86_1814_reg_1356_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1814_reg_1356_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1815_fu_360_p2;
reg   [0:0] icmp_ln86_1815_reg_1362;
reg   [0:0] icmp_ln86_1815_reg_1362_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1816_fu_366_p2;
reg   [0:0] icmp_ln86_1816_reg_1368;
wire   [0:0] icmp_ln86_1817_fu_372_p2;
reg   [0:0] icmp_ln86_1817_reg_1374;
reg   [0:0] icmp_ln86_1817_reg_1374_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1818_fu_378_p2;
reg   [0:0] icmp_ln86_1818_reg_1380;
reg   [0:0] icmp_ln86_1818_reg_1380_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1818_reg_1380_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1819_fu_384_p2;
reg   [0:0] icmp_ln86_1819_reg_1386;
reg   [0:0] icmp_ln86_1819_reg_1386_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1819_reg_1386_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1820_fu_390_p2;
reg   [0:0] icmp_ln86_1820_reg_1392;
reg   [0:0] icmp_ln86_1820_reg_1392_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1820_reg_1392_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1820_reg_1392_pp0_iter3_reg;
wire   [0:0] icmp_ln86_1821_fu_396_p2;
reg   [0:0] icmp_ln86_1821_reg_1398;
reg   [0:0] icmp_ln86_1821_reg_1398_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1821_reg_1398_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1821_reg_1398_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1821_reg_1398_pp0_iter4_reg;
wire   [0:0] icmp_ln86_1822_fu_402_p2;
reg   [0:0] icmp_ln86_1822_reg_1404;
reg   [0:0] icmp_ln86_1822_reg_1404_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1822_reg_1404_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1822_reg_1404_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1822_reg_1404_pp0_iter4_reg;
wire   [0:0] icmp_ln86_1823_fu_408_p2;
reg   [0:0] icmp_ln86_1823_reg_1410;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter4_reg;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter5_reg;
reg   [0:0] icmp_ln86_1823_reg_1410_pp0_iter6_reg;
wire   [0:0] icmp_ln86_1824_fu_414_p2;
reg   [0:0] icmp_ln86_1824_reg_1416;
wire   [0:0] icmp_ln86_1825_fu_420_p2;
reg   [0:0] icmp_ln86_1825_reg_1421;
wire   [0:0] icmp_ln86_1826_fu_426_p2;
reg   [0:0] icmp_ln86_1826_reg_1426;
reg   [0:0] icmp_ln86_1826_reg_1426_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1827_fu_432_p2;
reg   [0:0] icmp_ln86_1827_reg_1431;
reg   [0:0] icmp_ln86_1827_reg_1431_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1828_fu_438_p2;
reg   [0:0] icmp_ln86_1828_reg_1436;
reg   [0:0] icmp_ln86_1828_reg_1436_pp0_iter1_reg;
wire   [0:0] icmp_ln86_1829_fu_444_p2;
reg   [0:0] icmp_ln86_1829_reg_1441;
reg   [0:0] icmp_ln86_1829_reg_1441_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1829_reg_1441_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1830_fu_450_p2;
reg   [0:0] icmp_ln86_1830_reg_1446;
reg   [0:0] icmp_ln86_1830_reg_1446_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1830_reg_1446_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1831_fu_456_p2;
reg   [0:0] icmp_ln86_1831_reg_1451;
reg   [0:0] icmp_ln86_1831_reg_1451_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1831_reg_1451_pp0_iter2_reg;
wire   [0:0] icmp_ln86_1832_fu_462_p2;
reg   [0:0] icmp_ln86_1832_reg_1456;
reg   [0:0] icmp_ln86_1832_reg_1456_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1832_reg_1456_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1832_reg_1456_pp0_iter3_reg;
wire   [0:0] icmp_ln86_1833_fu_468_p2;
reg   [0:0] icmp_ln86_1833_reg_1461;
reg   [0:0] icmp_ln86_1833_reg_1461_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1833_reg_1461_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1833_reg_1461_pp0_iter3_reg;
wire   [0:0] icmp_ln86_1834_fu_474_p2;
reg   [0:0] icmp_ln86_1834_reg_1466;
reg   [0:0] icmp_ln86_1834_reg_1466_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1834_reg_1466_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1834_reg_1466_pp0_iter3_reg;
wire   [0:0] icmp_ln86_1835_fu_480_p2;
reg   [0:0] icmp_ln86_1835_reg_1471;
reg   [0:0] icmp_ln86_1835_reg_1471_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1835_reg_1471_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1835_reg_1471_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1835_reg_1471_pp0_iter4_reg;
wire   [0:0] icmp_ln86_1836_fu_486_p2;
reg   [0:0] icmp_ln86_1836_reg_1476;
reg   [0:0] icmp_ln86_1836_reg_1476_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1836_reg_1476_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1836_reg_1476_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1836_reg_1476_pp0_iter4_reg;
wire   [0:0] icmp_ln86_1837_fu_492_p2;
reg   [0:0] icmp_ln86_1837_reg_1481;
reg   [0:0] icmp_ln86_1837_reg_1481_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1837_reg_1481_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1837_reg_1481_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1837_reg_1481_pp0_iter4_reg;
wire   [0:0] icmp_ln86_1838_fu_498_p2;
reg   [0:0] icmp_ln86_1838_reg_1486;
reg   [0:0] icmp_ln86_1838_reg_1486_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1838_reg_1486_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1838_reg_1486_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1838_reg_1486_pp0_iter4_reg;
reg   [0:0] icmp_ln86_1838_reg_1486_pp0_iter5_reg;
wire   [0:0] icmp_ln86_1839_fu_504_p2;
reg   [0:0] icmp_ln86_1839_reg_1491;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter1_reg;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter2_reg;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter3_reg;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter4_reg;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter5_reg;
reg   [0:0] icmp_ln86_1839_reg_1491_pp0_iter6_reg;
wire   [0:0] and_ln102_2019_fu_510_p2;
reg   [0:0] and_ln102_2019_reg_1496;
reg   [0:0] and_ln102_2019_reg_1496_pp0_iter1_reg;
wire   [0:0] and_ln104_fu_521_p2;
reg   [0:0] and_ln104_reg_1505;
wire   [0:0] and_ln104_332_fu_531_p2;
reg   [0:0] and_ln104_332_reg_1511;
wire   [0:0] and_ln102_2020_fu_536_p2;
reg   [0:0] and_ln102_2020_reg_1516;
reg   [0:0] and_ln102_2020_reg_1516_pp0_iter2_reg;
wire   [0:0] and_ln102_2024_fu_550_p2;
reg   [0:0] and_ln102_2024_reg_1523;
wire   [2:0] select_ln117_1760_fu_606_p3;
reg   [2:0] select_ln117_1760_reg_1528;
wire   [0:0] or_ln117_1600_fu_613_p2;
reg   [0:0] or_ln117_1600_reg_1533;
wire   [0:0] xor_ln104_fu_618_p2;
reg   [0:0] xor_ln104_reg_1539;
reg   [0:0] xor_ln104_reg_1539_pp0_iter3_reg;
reg   [0:0] xor_ln104_reg_1539_pp0_iter4_reg;
reg   [0:0] xor_ln104_reg_1539_pp0_iter5_reg;
reg   [0:0] xor_ln104_reg_1539_pp0_iter6_reg;
reg   [0:0] xor_ln104_reg_1539_pp0_iter7_reg;
wire   [0:0] and_ln102_fu_623_p2;
reg   [0:0] and_ln102_reg_1544;
reg   [0:0] and_ln102_reg_1544_pp0_iter3_reg;
wire   [0:0] and_ln104_333_fu_644_p2;
reg   [0:0] and_ln104_333_reg_1551;
wire   [0:0] and_ln102_2022_fu_649_p2;
reg   [0:0] and_ln102_2022_reg_1556;
reg   [0:0] and_ln102_2022_reg_1556_pp0_iter3_reg;
reg   [0:0] and_ln102_2022_reg_1556_pp0_iter4_reg;
wire   [0:0] and_ln104_335_fu_659_p2;
reg   [0:0] and_ln104_335_reg_1563;
reg   [0:0] and_ln104_335_reg_1563_pp0_iter3_reg;
reg   [0:0] and_ln104_335_reg_1563_pp0_iter4_reg;
reg   [0:0] and_ln104_335_reg_1563_pp0_iter5_reg;
reg   [0:0] and_ln104_335_reg_1563_pp0_iter6_reg;
wire   [0:0] and_ln102_2026_fu_674_p2;
reg   [0:0] and_ln102_2026_reg_1569;
wire   [0:0] or_ln117_1603_fu_746_p2;
reg   [0:0] or_ln117_1603_reg_1575;
wire   [3:0] select_ln117_1766_fu_759_p3;
reg   [3:0] select_ln117_1766_reg_1580;
wire   [0:0] or_ln117_1605_fu_767_p2;
reg   [0:0] or_ln117_1605_reg_1585;
wire   [0:0] or_ln117_1609_fu_771_p2;
reg   [0:0] or_ln117_1609_reg_1592;
reg   [0:0] or_ln117_1609_reg_1592_pp0_iter3_reg;
reg   [0:0] or_ln117_1609_reg_1592_pp0_iter4_reg;
reg   [0:0] or_ln117_1609_reg_1592_pp0_iter5_reg;
reg   [0:0] or_ln117_1609_reg_1592_pp0_iter6_reg;
reg   [0:0] or_ln117_1609_reg_1592_pp0_iter7_reg;
wire   [0:0] and_ln102_2021_fu_775_p2;
reg   [0:0] and_ln102_2021_reg_1602;
wire   [0:0] and_ln104_334_fu_784_p2;
reg   [0:0] and_ln104_334_reg_1608;
reg   [0:0] and_ln104_334_reg_1608_pp0_iter4_reg;
wire   [0:0] and_ln102_2027_fu_799_p2;
reg   [0:0] and_ln102_2027_reg_1614;
wire   [4:0] select_ln117_1772_fu_890_p3;
reg   [4:0] select_ln117_1772_reg_1619;
wire   [0:0] or_ln117_1611_fu_897_p2;
reg   [0:0] or_ln117_1611_reg_1624;
wire   [0:0] and_ln102_2029_fu_911_p2;
reg   [0:0] and_ln102_2029_reg_1630;
wire   [0:0] or_ln117_1615_fu_984_p2;
reg   [0:0] or_ln117_1615_reg_1636;
wire   [4:0] select_ln117_1778_fu_998_p3;
reg   [4:0] select_ln117_1778_reg_1641;
wire   [0:0] or_ln117_1617_fu_1006_p2;
reg   [0:0] or_ln117_1617_reg_1646;
wire   [0:0] or_ln117_1621_fu_1094_p2;
reg   [0:0] or_ln117_1621_reg_1654;
wire   [4:0] select_ln117_1784_fu_1106_p3;
reg   [4:0] select_ln117_1784_reg_1660;
wire   [0:0] or_ln117_1623_fu_1128_p2;
reg   [0:0] or_ln117_1623_reg_1665;
wire   [4:0] select_ln117_1786_fu_1140_p3;
reg   [4:0] select_ln117_1786_reg_1670;
wire   [11:0] tmp_fu_1175_p67;
reg   [11:0] tmp_reg_1675;
wire    ap_block_pp0_stage0;
wire   [0:0] xor_ln104_859_fu_516_p2;
wire   [0:0] xor_ln104_861_fu_526_p2;
wire   [0:0] and_ln102_2023_fu_541_p2;
wire   [0:0] xor_ln104_865_fu_545_p2;
wire   [0:0] and_ln102_2032_fu_560_p2;
wire   [0:0] and_ln102_2031_fu_555_p2;
wire   [0:0] xor_ln117_fu_570_p2;
wire   [0:0] and_ln102_2033_fu_565_p2;
wire   [1:0] zext_ln117_fu_576_p1;
wire   [0:0] or_ln117_fu_580_p2;
wire   [1:0] select_ln117_fu_586_p3;
wire   [1:0] select_ln117_1759_fu_594_p3;
wire   [2:0] zext_ln117_187_fu_602_p1;
wire   [0:0] xor_ln104_860_fu_628_p2;
wire   [0:0] xor_ln104_862_fu_639_p2;
wire   [0:0] and_ln104_331_fu_633_p2;
wire   [0:0] xor_ln104_864_fu_654_p2;
wire   [0:0] xor_ln104_866_fu_665_p2;
wire   [0:0] and_ln102_2035_fu_683_p2;
wire   [0:0] and_ln102_2025_fu_670_p2;
wire   [0:0] and_ln102_2034_fu_679_p2;
wire   [0:0] or_ln117_1599_fu_698_p2;
wire   [0:0] and_ln102_2036_fu_688_p2;
wire   [2:0] select_ln117_1761_fu_703_p3;
wire   [0:0] or_ln117_1601_fu_710_p2;
wire   [2:0] select_ln117_1762_fu_715_p3;
wire   [2:0] select_ln117_1763_fu_722_p3;
wire   [0:0] and_ln102_2037_fu_693_p2;
wire   [3:0] zext_ln117_188_fu_730_p1;
wire   [0:0] or_ln117_1602_fu_734_p2;
wire   [3:0] select_ln117_1764_fu_739_p3;
wire   [3:0] select_ln117_1765_fu_751_p3;
wire   [0:0] xor_ln104_863_fu_779_p2;
wire   [0:0] xor_ln104_867_fu_789_p2;
wire   [0:0] and_ln102_2038_fu_804_p2;
wire   [0:0] xor_ln104_868_fu_794_p2;
wire   [0:0] and_ln102_2041_fu_818_p2;
wire   [0:0] and_ln102_2039_fu_809_p2;
wire   [0:0] or_ln117_1604_fu_828_p2;
wire   [0:0] and_ln102_2040_fu_814_p2;
wire   [3:0] select_ln117_1767_fu_833_p3;
wire   [0:0] or_ln117_1606_fu_840_p2;
wire   [3:0] select_ln117_1768_fu_845_p3;
wire   [0:0] or_ln117_1607_fu_852_p2;
wire   [0:0] and_ln102_2042_fu_823_p2;
wire   [3:0] select_ln117_1769_fu_856_p3;
wire   [0:0] or_ln117_1608_fu_864_p2;
wire   [3:0] select_ln117_1770_fu_870_p3;
wire   [3:0] select_ln117_1771_fu_878_p3;
wire   [4:0] zext_ln117_189_fu_886_p1;
wire   [0:0] xor_ln104_869_fu_902_p2;
wire   [0:0] and_ln102_2044_fu_919_p2;
wire   [0:0] and_ln102_2028_fu_907_p2;
wire   [0:0] and_ln102_2043_fu_915_p2;
wire   [0:0] or_ln117_1610_fu_934_p2;
wire   [0:0] and_ln102_2045_fu_924_p2;
wire   [4:0] select_ln117_1773_fu_939_p3;
wire   [0:0] or_ln117_1612_fu_946_p2;
wire   [4:0] select_ln117_1774_fu_951_p3;
wire   [0:0] or_ln117_1613_fu_958_p2;
wire   [0:0] and_ln102_2046_fu_929_p2;
wire   [4:0] select_ln117_1775_fu_962_p3;
wire   [0:0] or_ln117_1614_fu_970_p2;
wire   [4:0] select_ln117_1776_fu_976_p3;
wire   [4:0] select_ln117_1777_fu_990_p3;
wire   [0:0] xor_ln104_870_fu_1010_p2;
wire   [0:0] and_ln102_2047_fu_1020_p2;
wire   [0:0] xor_ln104_871_fu_1015_p2;
wire   [0:0] and_ln102_2050_fu_1034_p2;
wire   [0:0] and_ln102_2048_fu_1025_p2;
wire   [0:0] or_ln117_1616_fu_1044_p2;
wire   [0:0] and_ln102_2049_fu_1030_p2;
wire   [4:0] select_ln117_1779_fu_1049_p3;
wire   [0:0] or_ln117_1618_fu_1056_p2;
wire   [4:0] select_ln117_1780_fu_1061_p3;
wire   [0:0] or_ln117_1619_fu_1068_p2;
wire   [0:0] and_ln102_2051_fu_1039_p2;
wire   [4:0] select_ln117_1781_fu_1072_p3;
wire   [0:0] or_ln117_1620_fu_1080_p2;
wire   [4:0] select_ln117_1782_fu_1086_p3;
wire   [4:0] select_ln117_1783_fu_1098_p3;
wire   [0:0] and_ln102_2030_fu_1114_p2;
wire   [0:0] and_ln102_2052_fu_1118_p2;
wire   [0:0] or_ln117_1622_fu_1123_p2;
wire   [4:0] select_ln117_1785_fu_1133_p3;
wire   [0:0] xor_ln104_872_fu_1148_p2;
wire   [0:0] and_ln102_2053_fu_1153_p2;
wire   [0:0] and_ln102_2054_fu_1158_p2;
wire   [0:0] or_ln117_1624_fu_1163_p2;
wire   [11:0] tmp_fu_1175_p65;
wire   [4:0] tmp_fu_1175_p66;
wire   [0:0] or_ln117_1625_fu_1311_p2;
reg   [17:0] p_read1_int_reg;
reg   [17:0] p_read2_int_reg;
reg   [17:0] p_read3_int_reg;
reg   [17:0] p_read4_int_reg;
reg   [17:0] p_read5_int_reg;
reg   [17:0] p_read6_int_reg;
reg   [17:0] p_read7_int_reg;
reg   [17:0] p_read8_int_reg;
reg   [17:0] p_read9_int_reg;
reg   [17:0] p_read10_int_reg;
reg   [17:0] p_read11_int_reg;
wire   [4:0] tmp_fu_1175_p1;
wire   [4:0] tmp_fu_1175_p3;
wire   [4:0] tmp_fu_1175_p5;
wire   [4:0] tmp_fu_1175_p7;
wire   [4:0] tmp_fu_1175_p9;
wire   [4:0] tmp_fu_1175_p11;
wire   [4:0] tmp_fu_1175_p13;
wire   [4:0] tmp_fu_1175_p15;
wire   [4:0] tmp_fu_1175_p17;
wire   [4:0] tmp_fu_1175_p19;
wire   [4:0] tmp_fu_1175_p21;
wire   [4:0] tmp_fu_1175_p23;
wire   [4:0] tmp_fu_1175_p25;
wire   [4:0] tmp_fu_1175_p27;
wire   [4:0] tmp_fu_1175_p29;
wire   [4:0] tmp_fu_1175_p31;
wire  signed [4:0] tmp_fu_1175_p33;
wire  signed [4:0] tmp_fu_1175_p35;
wire  signed [4:0] tmp_fu_1175_p37;
wire  signed [4:0] tmp_fu_1175_p39;
wire  signed [4:0] tmp_fu_1175_p41;
wire  signed [4:0] tmp_fu_1175_p43;
wire  signed [4:0] tmp_fu_1175_p45;
wire  signed [4:0] tmp_fu_1175_p47;
wire  signed [4:0] tmp_fu_1175_p49;
wire  signed [4:0] tmp_fu_1175_p51;
wire  signed [4:0] tmp_fu_1175_p53;
wire  signed [4:0] tmp_fu_1175_p55;
wire  signed [4:0] tmp_fu_1175_p57;
wire  signed [4:0] tmp_fu_1175_p59;
wire  signed [4:0] tmp_fu_1175_p61;
wire  signed [4:0] tmp_fu_1175_p63;
wire    ap_ce_reg;

(* dissolve_hierarchy = "yes" *) conifer_jettag_accelerator_sparsemux_65_5_12_1_1_x27 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 12 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 12 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 12 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 12 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 12 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 12 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 12 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 12 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 12 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 12 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 12 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 12 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 12 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 12 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 12 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 12 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
sparsemux_65_5_12_1_1_x27_U1451(
    .din0(12'd125),
    .din1(12'd21),
    .din2(12'd4059),
    .din3(12'd3798),
    .din4(12'd4030),
    .din5(12'd481),
    .din6(12'd3654),
    .din7(12'd52),
    .din8(12'd24),
    .din9(12'd144),
    .din10(12'd2),
    .din11(12'd4048),
    .din12(12'd62),
    .din13(12'd3923),
    .din14(12'd28),
    .din15(12'd4021),
    .din16(12'd200),
    .din17(12'd10),
    .din18(12'd4082),
    .din19(12'd3595),
    .din20(12'd3931),
    .din21(12'd152),
    .din22(12'd179),
    .din23(12'd1644),
    .din24(12'd4038),
    .din25(12'd3782),
    .din26(12'd99),
    .din27(12'd3655),
    .din28(12'd573),
    .din29(12'd96),
    .din30(12'd3606),
    .din31(12'd4040),
    .def(tmp_fu_1175_p65),
    .sel(tmp_fu_1175_p66),
    .dout(tmp_fu_1175_p67)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        and_ln102_2019_reg_1496 <= and_ln102_2019_fu_510_p2;
        and_ln102_2019_reg_1496_pp0_iter1_reg <= and_ln102_2019_reg_1496;
        and_ln102_2020_reg_1516 <= and_ln102_2020_fu_536_p2;
        and_ln102_2020_reg_1516_pp0_iter2_reg <= and_ln102_2020_reg_1516;
        and_ln102_2021_reg_1602 <= and_ln102_2021_fu_775_p2;
        and_ln102_2022_reg_1556 <= and_ln102_2022_fu_649_p2;
        and_ln102_2022_reg_1556_pp0_iter3_reg <= and_ln102_2022_reg_1556;
        and_ln102_2022_reg_1556_pp0_iter4_reg <= and_ln102_2022_reg_1556_pp0_iter3_reg;
        and_ln102_2024_reg_1523 <= and_ln102_2024_fu_550_p2;
        and_ln102_2026_reg_1569 <= and_ln102_2026_fu_674_p2;
        and_ln102_2027_reg_1614 <= and_ln102_2027_fu_799_p2;
        and_ln102_2029_reg_1630 <= and_ln102_2029_fu_911_p2;
        and_ln102_reg_1544 <= and_ln102_fu_623_p2;
        and_ln102_reg_1544_pp0_iter3_reg <= and_ln102_reg_1544;
        and_ln104_332_reg_1511 <= and_ln104_332_fu_531_p2;
        and_ln104_333_reg_1551 <= and_ln104_333_fu_644_p2;
        and_ln104_334_reg_1608 <= and_ln104_334_fu_784_p2;
        and_ln104_334_reg_1608_pp0_iter4_reg <= and_ln104_334_reg_1608;
        and_ln104_335_reg_1563 <= and_ln104_335_fu_659_p2;
        and_ln104_335_reg_1563_pp0_iter3_reg <= and_ln104_335_reg_1563;
        and_ln104_335_reg_1563_pp0_iter4_reg <= and_ln104_335_reg_1563_pp0_iter3_reg;
        and_ln104_335_reg_1563_pp0_iter5_reg <= and_ln104_335_reg_1563_pp0_iter4_reg;
        and_ln104_335_reg_1563_pp0_iter6_reg <= and_ln104_335_reg_1563_pp0_iter5_reg;
        and_ln104_reg_1505 <= and_ln104_fu_521_p2;
        icmp_ln86_1810_reg_1328 <= icmp_ln86_1810_fu_330_p2;
        icmp_ln86_1810_reg_1328_pp0_iter1_reg <= icmp_ln86_1810_reg_1328;
        icmp_ln86_1811_reg_1339 <= icmp_ln86_1811_fu_336_p2;
        icmp_ln86_1811_reg_1339_pp0_iter1_reg <= icmp_ln86_1811_reg_1339;
        icmp_ln86_1812_reg_1345 <= icmp_ln86_1812_fu_342_p2;
        icmp_ln86_1813_reg_1350 <= icmp_ln86_1813_fu_348_p2;
        icmp_ln86_1813_reg_1350_pp0_iter1_reg <= icmp_ln86_1813_reg_1350;
        icmp_ln86_1814_reg_1356 <= icmp_ln86_1814_fu_354_p2;
        icmp_ln86_1814_reg_1356_pp0_iter1_reg <= icmp_ln86_1814_reg_1356;
        icmp_ln86_1814_reg_1356_pp0_iter2_reg <= icmp_ln86_1814_reg_1356_pp0_iter1_reg;
        icmp_ln86_1815_reg_1362 <= icmp_ln86_1815_fu_360_p2;
        icmp_ln86_1815_reg_1362_pp0_iter1_reg <= icmp_ln86_1815_reg_1362;
        icmp_ln86_1816_reg_1368 <= icmp_ln86_1816_fu_366_p2;
        icmp_ln86_1817_reg_1374 <= icmp_ln86_1817_fu_372_p2;
        icmp_ln86_1817_reg_1374_pp0_iter1_reg <= icmp_ln86_1817_reg_1374;
        icmp_ln86_1818_reg_1380 <= icmp_ln86_1818_fu_378_p2;
        icmp_ln86_1818_reg_1380_pp0_iter1_reg <= icmp_ln86_1818_reg_1380;
        icmp_ln86_1818_reg_1380_pp0_iter2_reg <= icmp_ln86_1818_reg_1380_pp0_iter1_reg;
        icmp_ln86_1819_reg_1386 <= icmp_ln86_1819_fu_384_p2;
        icmp_ln86_1819_reg_1386_pp0_iter1_reg <= icmp_ln86_1819_reg_1386;
        icmp_ln86_1819_reg_1386_pp0_iter2_reg <= icmp_ln86_1819_reg_1386_pp0_iter1_reg;
        icmp_ln86_1820_reg_1392 <= icmp_ln86_1820_fu_390_p2;
        icmp_ln86_1820_reg_1392_pp0_iter1_reg <= icmp_ln86_1820_reg_1392;
        icmp_ln86_1820_reg_1392_pp0_iter2_reg <= icmp_ln86_1820_reg_1392_pp0_iter1_reg;
        icmp_ln86_1820_reg_1392_pp0_iter3_reg <= icmp_ln86_1820_reg_1392_pp0_iter2_reg;
        icmp_ln86_1821_reg_1398 <= icmp_ln86_1821_fu_396_p2;
        icmp_ln86_1821_reg_1398_pp0_iter1_reg <= icmp_ln86_1821_reg_1398;
        icmp_ln86_1821_reg_1398_pp0_iter2_reg <= icmp_ln86_1821_reg_1398_pp0_iter1_reg;
        icmp_ln86_1821_reg_1398_pp0_iter3_reg <= icmp_ln86_1821_reg_1398_pp0_iter2_reg;
        icmp_ln86_1821_reg_1398_pp0_iter4_reg <= icmp_ln86_1821_reg_1398_pp0_iter3_reg;
        icmp_ln86_1822_reg_1404 <= icmp_ln86_1822_fu_402_p2;
        icmp_ln86_1822_reg_1404_pp0_iter1_reg <= icmp_ln86_1822_reg_1404;
        icmp_ln86_1822_reg_1404_pp0_iter2_reg <= icmp_ln86_1822_reg_1404_pp0_iter1_reg;
        icmp_ln86_1822_reg_1404_pp0_iter3_reg <= icmp_ln86_1822_reg_1404_pp0_iter2_reg;
        icmp_ln86_1822_reg_1404_pp0_iter4_reg <= icmp_ln86_1822_reg_1404_pp0_iter3_reg;
        icmp_ln86_1823_reg_1410 <= icmp_ln86_1823_fu_408_p2;
        icmp_ln86_1823_reg_1410_pp0_iter1_reg <= icmp_ln86_1823_reg_1410;
        icmp_ln86_1823_reg_1410_pp0_iter2_reg <= icmp_ln86_1823_reg_1410_pp0_iter1_reg;
        icmp_ln86_1823_reg_1410_pp0_iter3_reg <= icmp_ln86_1823_reg_1410_pp0_iter2_reg;
        icmp_ln86_1823_reg_1410_pp0_iter4_reg <= icmp_ln86_1823_reg_1410_pp0_iter3_reg;
        icmp_ln86_1823_reg_1410_pp0_iter5_reg <= icmp_ln86_1823_reg_1410_pp0_iter4_reg;
        icmp_ln86_1823_reg_1410_pp0_iter6_reg <= icmp_ln86_1823_reg_1410_pp0_iter5_reg;
        icmp_ln86_1824_reg_1416 <= icmp_ln86_1824_fu_414_p2;
        icmp_ln86_1825_reg_1421 <= icmp_ln86_1825_fu_420_p2;
        icmp_ln86_1826_reg_1426 <= icmp_ln86_1826_fu_426_p2;
        icmp_ln86_1826_reg_1426_pp0_iter1_reg <= icmp_ln86_1826_reg_1426;
        icmp_ln86_1827_reg_1431 <= icmp_ln86_1827_fu_432_p2;
        icmp_ln86_1827_reg_1431_pp0_iter1_reg <= icmp_ln86_1827_reg_1431;
        icmp_ln86_1828_reg_1436 <= icmp_ln86_1828_fu_438_p2;
        icmp_ln86_1828_reg_1436_pp0_iter1_reg <= icmp_ln86_1828_reg_1436;
        icmp_ln86_1829_reg_1441 <= icmp_ln86_1829_fu_444_p2;
        icmp_ln86_1829_reg_1441_pp0_iter1_reg <= icmp_ln86_1829_reg_1441;
        icmp_ln86_1829_reg_1441_pp0_iter2_reg <= icmp_ln86_1829_reg_1441_pp0_iter1_reg;
        icmp_ln86_1830_reg_1446 <= icmp_ln86_1830_fu_450_p2;
        icmp_ln86_1830_reg_1446_pp0_iter1_reg <= icmp_ln86_1830_reg_1446;
        icmp_ln86_1830_reg_1446_pp0_iter2_reg <= icmp_ln86_1830_reg_1446_pp0_iter1_reg;
        icmp_ln86_1831_reg_1451 <= icmp_ln86_1831_fu_456_p2;
        icmp_ln86_1831_reg_1451_pp0_iter1_reg <= icmp_ln86_1831_reg_1451;
        icmp_ln86_1831_reg_1451_pp0_iter2_reg <= icmp_ln86_1831_reg_1451_pp0_iter1_reg;
        icmp_ln86_1832_reg_1456 <= icmp_ln86_1832_fu_462_p2;
        icmp_ln86_1832_reg_1456_pp0_iter1_reg <= icmp_ln86_1832_reg_1456;
        icmp_ln86_1832_reg_1456_pp0_iter2_reg <= icmp_ln86_1832_reg_1456_pp0_iter1_reg;
        icmp_ln86_1832_reg_1456_pp0_iter3_reg <= icmp_ln86_1832_reg_1456_pp0_iter2_reg;
        icmp_ln86_1833_reg_1461 <= icmp_ln86_1833_fu_468_p2;
        icmp_ln86_1833_reg_1461_pp0_iter1_reg <= icmp_ln86_1833_reg_1461;
        icmp_ln86_1833_reg_1461_pp0_iter2_reg <= icmp_ln86_1833_reg_1461_pp0_iter1_reg;
        icmp_ln86_1833_reg_1461_pp0_iter3_reg <= icmp_ln86_1833_reg_1461_pp0_iter2_reg;
        icmp_ln86_1834_reg_1466 <= icmp_ln86_1834_fu_474_p2;
        icmp_ln86_1834_reg_1466_pp0_iter1_reg <= icmp_ln86_1834_reg_1466;
        icmp_ln86_1834_reg_1466_pp0_iter2_reg <= icmp_ln86_1834_reg_1466_pp0_iter1_reg;
        icmp_ln86_1834_reg_1466_pp0_iter3_reg <= icmp_ln86_1834_reg_1466_pp0_iter2_reg;
        icmp_ln86_1835_reg_1471 <= icmp_ln86_1835_fu_480_p2;
        icmp_ln86_1835_reg_1471_pp0_iter1_reg <= icmp_ln86_1835_reg_1471;
        icmp_ln86_1835_reg_1471_pp0_iter2_reg <= icmp_ln86_1835_reg_1471_pp0_iter1_reg;
        icmp_ln86_1835_reg_1471_pp0_iter3_reg <= icmp_ln86_1835_reg_1471_pp0_iter2_reg;
        icmp_ln86_1835_reg_1471_pp0_iter4_reg <= icmp_ln86_1835_reg_1471_pp0_iter3_reg;
        icmp_ln86_1836_reg_1476 <= icmp_ln86_1836_fu_486_p2;
        icmp_ln86_1836_reg_1476_pp0_iter1_reg <= icmp_ln86_1836_reg_1476;
        icmp_ln86_1836_reg_1476_pp0_iter2_reg <= icmp_ln86_1836_reg_1476_pp0_iter1_reg;
        icmp_ln86_1836_reg_1476_pp0_iter3_reg <= icmp_ln86_1836_reg_1476_pp0_iter2_reg;
        icmp_ln86_1836_reg_1476_pp0_iter4_reg <= icmp_ln86_1836_reg_1476_pp0_iter3_reg;
        icmp_ln86_1837_reg_1481 <= icmp_ln86_1837_fu_492_p2;
        icmp_ln86_1837_reg_1481_pp0_iter1_reg <= icmp_ln86_1837_reg_1481;
        icmp_ln86_1837_reg_1481_pp0_iter2_reg <= icmp_ln86_1837_reg_1481_pp0_iter1_reg;
        icmp_ln86_1837_reg_1481_pp0_iter3_reg <= icmp_ln86_1837_reg_1481_pp0_iter2_reg;
        icmp_ln86_1837_reg_1481_pp0_iter4_reg <= icmp_ln86_1837_reg_1481_pp0_iter3_reg;
        icmp_ln86_1838_reg_1486 <= icmp_ln86_1838_fu_498_p2;
        icmp_ln86_1838_reg_1486_pp0_iter1_reg <= icmp_ln86_1838_reg_1486;
        icmp_ln86_1838_reg_1486_pp0_iter2_reg <= icmp_ln86_1838_reg_1486_pp0_iter1_reg;
        icmp_ln86_1838_reg_1486_pp0_iter3_reg <= icmp_ln86_1838_reg_1486_pp0_iter2_reg;
        icmp_ln86_1838_reg_1486_pp0_iter4_reg <= icmp_ln86_1838_reg_1486_pp0_iter3_reg;
        icmp_ln86_1838_reg_1486_pp0_iter5_reg <= icmp_ln86_1838_reg_1486_pp0_iter4_reg;
        icmp_ln86_1839_reg_1491 <= icmp_ln86_1839_fu_504_p2;
        icmp_ln86_1839_reg_1491_pp0_iter1_reg <= icmp_ln86_1839_reg_1491;
        icmp_ln86_1839_reg_1491_pp0_iter2_reg <= icmp_ln86_1839_reg_1491_pp0_iter1_reg;
        icmp_ln86_1839_reg_1491_pp0_iter3_reg <= icmp_ln86_1839_reg_1491_pp0_iter2_reg;
        icmp_ln86_1839_reg_1491_pp0_iter4_reg <= icmp_ln86_1839_reg_1491_pp0_iter3_reg;
        icmp_ln86_1839_reg_1491_pp0_iter5_reg <= icmp_ln86_1839_reg_1491_pp0_iter4_reg;
        icmp_ln86_1839_reg_1491_pp0_iter6_reg <= icmp_ln86_1839_reg_1491_pp0_iter5_reg;
        icmp_ln86_reg_1322 <= icmp_ln86_fu_324_p2;
        icmp_ln86_reg_1322_pp0_iter1_reg <= icmp_ln86_reg_1322;
        or_ln117_1600_reg_1533 <= or_ln117_1600_fu_613_p2;
        or_ln117_1603_reg_1575 <= or_ln117_1603_fu_746_p2;
        or_ln117_1605_reg_1585 <= or_ln117_1605_fu_767_p2;
        or_ln117_1609_reg_1592 <= or_ln117_1609_fu_771_p2;
        or_ln117_1609_reg_1592_pp0_iter3_reg <= or_ln117_1609_reg_1592;
        or_ln117_1609_reg_1592_pp0_iter4_reg <= or_ln117_1609_reg_1592_pp0_iter3_reg;
        or_ln117_1609_reg_1592_pp0_iter5_reg <= or_ln117_1609_reg_1592_pp0_iter4_reg;
        or_ln117_1609_reg_1592_pp0_iter6_reg <= or_ln117_1609_reg_1592_pp0_iter5_reg;
        or_ln117_1609_reg_1592_pp0_iter7_reg <= or_ln117_1609_reg_1592_pp0_iter6_reg;
        or_ln117_1611_reg_1624 <= or_ln117_1611_fu_897_p2;
        or_ln117_1615_reg_1636 <= or_ln117_1615_fu_984_p2;
        or_ln117_1617_reg_1646 <= or_ln117_1617_fu_1006_p2;
        or_ln117_1621_reg_1654 <= or_ln117_1621_fu_1094_p2;
        or_ln117_1623_reg_1665 <= or_ln117_1623_fu_1128_p2;
        select_ln117_1760_reg_1528 <= select_ln117_1760_fu_606_p3;
        select_ln117_1766_reg_1580 <= select_ln117_1766_fu_759_p3;
        select_ln117_1772_reg_1619 <= select_ln117_1772_fu_890_p3;
        select_ln117_1778_reg_1641 <= select_ln117_1778_fu_998_p3;
        select_ln117_1784_reg_1660 <= select_ln117_1784_fu_1106_p3;
        select_ln117_1786_reg_1670 <= select_ln117_1786_fu_1140_p3;
        tmp_reg_1675 <= tmp_fu_1175_p67;
        xor_ln104_reg_1539 <= xor_ln104_fu_618_p2;
        xor_ln104_reg_1539_pp0_iter3_reg <= xor_ln104_reg_1539;
        xor_ln104_reg_1539_pp0_iter4_reg <= xor_ln104_reg_1539_pp0_iter3_reg;
        xor_ln104_reg_1539_pp0_iter5_reg <= xor_ln104_reg_1539_pp0_iter4_reg;
        xor_ln104_reg_1539_pp0_iter6_reg <= xor_ln104_reg_1539_pp0_iter5_reg;
        xor_ln104_reg_1539_pp0_iter7_reg <= xor_ln104_reg_1539_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
    end
end

assign and_ln102_2019_fu_510_p2 = (icmp_ln86_1812_fu_342_p2 & icmp_ln86_1810_fu_330_p2);

assign and_ln102_2020_fu_536_p2 = (icmp_ln86_1813_reg_1350 & and_ln104_fu_521_p2);

assign and_ln102_2021_fu_775_p2 = (icmp_ln86_1814_reg_1356_pp0_iter2_reg & and_ln102_reg_1544);

assign and_ln102_2022_fu_649_p2 = (icmp_ln86_1815_reg_1362_pp0_iter1_reg & and_ln104_331_fu_633_p2);

assign and_ln102_2023_fu_541_p2 = (icmp_ln86_1816_reg_1368 & and_ln102_2019_reg_1496);

assign and_ln102_2024_fu_550_p2 = (icmp_ln86_1817_reg_1374 & and_ln104_332_fu_531_p2);

assign and_ln102_2025_fu_670_p2 = (icmp_ln86_1818_reg_1380_pp0_iter1_reg & and_ln102_2020_reg_1516);

assign and_ln102_2026_fu_674_p2 = (icmp_ln86_1819_reg_1386_pp0_iter1_reg & and_ln104_333_fu_644_p2);

assign and_ln102_2027_fu_799_p2 = (icmp_ln86_1820_reg_1392_pp0_iter2_reg & and_ln102_2021_fu_775_p2);

assign and_ln102_2028_fu_907_p2 = (icmp_ln86_1821_reg_1398_pp0_iter3_reg & and_ln104_334_reg_1608);

assign and_ln102_2029_fu_911_p2 = (icmp_ln86_1822_reg_1404_pp0_iter3_reg & and_ln102_2022_reg_1556_pp0_iter3_reg);

assign and_ln102_2030_fu_1114_p2 = (icmp_ln86_1823_reg_1410_pp0_iter5_reg & and_ln104_335_reg_1563_pp0_iter5_reg);

assign and_ln102_2031_fu_555_p2 = (icmp_ln86_1824_reg_1416 & and_ln102_2023_fu_541_p2);

assign and_ln102_2032_fu_560_p2 = (xor_ln104_865_fu_545_p2 & icmp_ln86_1825_reg_1421);

assign and_ln102_2033_fu_565_p2 = (and_ln102_2032_fu_560_p2 & and_ln102_2019_reg_1496);

assign and_ln102_2034_fu_679_p2 = (icmp_ln86_1826_reg_1426_pp0_iter1_reg & and_ln102_2024_reg_1523);

assign and_ln102_2035_fu_683_p2 = (xor_ln104_866_fu_665_p2 & icmp_ln86_1827_reg_1431_pp0_iter1_reg);

assign and_ln102_2036_fu_688_p2 = (and_ln104_332_reg_1511 & and_ln102_2035_fu_683_p2);

assign and_ln102_2037_fu_693_p2 = (icmp_ln86_1828_reg_1436_pp0_iter1_reg & and_ln102_2025_fu_670_p2);

assign and_ln102_2038_fu_804_p2 = (xor_ln104_867_fu_789_p2 & icmp_ln86_1829_reg_1441_pp0_iter2_reg);

assign and_ln102_2039_fu_809_p2 = (and_ln102_2038_fu_804_p2 & and_ln102_2020_reg_1516_pp0_iter2_reg);

assign and_ln102_2040_fu_814_p2 = (icmp_ln86_1830_reg_1446_pp0_iter2_reg & and_ln102_2026_reg_1569);

assign and_ln102_2041_fu_818_p2 = (xor_ln104_868_fu_794_p2 & icmp_ln86_1831_reg_1451_pp0_iter2_reg);

assign and_ln102_2042_fu_823_p2 = (and_ln104_333_reg_1551 & and_ln102_2041_fu_818_p2);

assign and_ln102_2043_fu_915_p2 = (icmp_ln86_1832_reg_1456_pp0_iter3_reg & and_ln102_2027_reg_1614);

assign and_ln102_2044_fu_919_p2 = (xor_ln104_869_fu_902_p2 & icmp_ln86_1833_reg_1461_pp0_iter3_reg);

assign and_ln102_2045_fu_924_p2 = (and_ln102_2044_fu_919_p2 & and_ln102_2021_reg_1602);

assign and_ln102_2046_fu_929_p2 = (icmp_ln86_1834_reg_1466_pp0_iter3_reg & and_ln102_2028_fu_907_p2);

assign and_ln102_2047_fu_1020_p2 = (xor_ln104_870_fu_1010_p2 & icmp_ln86_1835_reg_1471_pp0_iter4_reg);

assign and_ln102_2048_fu_1025_p2 = (and_ln104_334_reg_1608_pp0_iter4_reg & and_ln102_2047_fu_1020_p2);

assign and_ln102_2049_fu_1030_p2 = (icmp_ln86_1836_reg_1476_pp0_iter4_reg & and_ln102_2029_reg_1630);

assign and_ln102_2050_fu_1034_p2 = (xor_ln104_871_fu_1015_p2 & icmp_ln86_1837_reg_1481_pp0_iter4_reg);

assign and_ln102_2051_fu_1039_p2 = (and_ln102_2050_fu_1034_p2 & and_ln102_2022_reg_1556_pp0_iter4_reg);

assign and_ln102_2052_fu_1118_p2 = (icmp_ln86_1838_reg_1486_pp0_iter5_reg & and_ln102_2030_fu_1114_p2);

assign and_ln102_2053_fu_1153_p2 = (xor_ln104_872_fu_1148_p2 & icmp_ln86_1839_reg_1491_pp0_iter6_reg);

assign and_ln102_2054_fu_1158_p2 = (and_ln104_335_reg_1563_pp0_iter6_reg & and_ln102_2053_fu_1153_p2);

assign and_ln102_fu_623_p2 = (xor_ln104_fu_618_p2 & icmp_ln86_1811_reg_1339_pp0_iter1_reg);

assign and_ln104_331_fu_633_p2 = (xor_ln104_fu_618_p2 & xor_ln104_860_fu_628_p2);

assign and_ln104_332_fu_531_p2 = (xor_ln104_861_fu_526_p2 & icmp_ln86_1810_reg_1328);

assign and_ln104_333_fu_644_p2 = (xor_ln104_862_fu_639_p2 & and_ln104_reg_1505);

assign and_ln104_334_fu_784_p2 = (xor_ln104_863_fu_779_p2 & and_ln102_reg_1544);

assign and_ln104_335_fu_659_p2 = (xor_ln104_864_fu_654_p2 & and_ln104_331_fu_633_p2);

assign and_ln104_fu_521_p2 = (xor_ln104_859_fu_516_p2 & icmp_ln86_reg_1322);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = ((or_ln117_1625_fu_1311_p2[0:0] == 1'b1) ? tmp_reg_1675 : 12'd0);

assign icmp_ln86_1810_fu_330_p2 = (($signed(p_read11_int_reg) < $signed(18'd260803)) ? 1'b1 : 1'b0);

assign icmp_ln86_1811_fu_336_p2 = (($signed(p_read1_int_reg) < $signed(18'd260983)) ? 1'b1 : 1'b0);

assign icmp_ln86_1812_fu_342_p2 = (($signed(p_read10_int_reg) < $signed(18'd313)) ? 1'b1 : 1'b0);

assign icmp_ln86_1813_fu_348_p2 = (($signed(p_read1_int_reg) < $signed(18'd1684)) ? 1'b1 : 1'b0);

assign icmp_ln86_1814_fu_354_p2 = (($signed(p_read10_int_reg) < $signed(18'd304)) ? 1'b1 : 1'b0);

assign icmp_ln86_1815_fu_360_p2 = (($signed(p_read10_int_reg) < $signed(18'd336)) ? 1'b1 : 1'b0);

assign icmp_ln86_1816_fu_366_p2 = (($signed(p_read3_int_reg) < $signed(18'd261748)) ? 1'b1 : 1'b0);

assign icmp_ln86_1817_fu_372_p2 = (($signed(p_read4_int_reg) < $signed(18'd168)) ? 1'b1 : 1'b0);

assign icmp_ln86_1818_fu_378_p2 = (($signed(p_read2_int_reg) < $signed(18'd261063)) ? 1'b1 : 1'b0);

assign icmp_ln86_1819_fu_384_p2 = (($signed(p_read4_int_reg) < $signed(18'd261274)) ? 1'b1 : 1'b0);

assign icmp_ln86_1820_fu_390_p2 = (($signed(p_read11_int_reg) < $signed(18'd2815)) ? 1'b1 : 1'b0);

assign icmp_ln86_1821_fu_396_p2 = (($signed(p_read1_int_reg) < $signed(18'd260975)) ? 1'b1 : 1'b0);

assign icmp_ln86_1822_fu_402_p2 = (($signed(p_read4_int_reg) < $signed(18'd262116)) ? 1'b1 : 1'b0);

assign icmp_ln86_1823_fu_408_p2 = (($signed(p_read4_int_reg) < $signed(18'd564)) ? 1'b1 : 1'b0);

assign icmp_ln86_1824_fu_414_p2 = (($signed(p_read1_int_reg) < $signed(18'd1451)) ? 1'b1 : 1'b0);

assign icmp_ln86_1825_fu_420_p2 = (($signed(p_read1_int_reg) < $signed(18'd1896)) ? 1'b1 : 1'b0);

assign icmp_ln86_1826_fu_426_p2 = (($signed(p_read2_int_reg) < $signed(18'd259004)) ? 1'b1 : 1'b0);

assign icmp_ln86_1827_fu_432_p2 = (($signed(p_read5_int_reg) < $signed(18'd20)) ? 1'b1 : 1'b0);

assign icmp_ln86_1828_fu_438_p2 = (($signed(p_read4_int_reg) < $signed(18'd261418)) ? 1'b1 : 1'b0);

assign icmp_ln86_1829_fu_444_p2 = (($signed(p_read1_int_reg) < $signed(18'd933)) ? 1'b1 : 1'b0);

assign icmp_ln86_1830_fu_450_p2 = (($signed(p_read8_int_reg) < $signed(18'd260003)) ? 1'b1 : 1'b0);

assign icmp_ln86_1831_fu_456_p2 = (($signed(p_read2_int_reg) < $signed(18'd259636)) ? 1'b1 : 1'b0);

assign icmp_ln86_1832_fu_462_p2 = (($signed(p_read1_int_reg) < $signed(18'd260383)) ? 1'b1 : 1'b0);

assign icmp_ln86_1833_fu_468_p2 = (($signed(p_read7_int_reg) < $signed(18'd61)) ? 1'b1 : 1'b0);

assign icmp_ln86_1834_fu_474_p2 = (($signed(p_read10_int_reg) < $signed(18'd2374)) ? 1'b1 : 1'b0);

assign icmp_ln86_1835_fu_480_p2 = (($signed(p_read6_int_reg) < $signed(18'd831)) ? 1'b1 : 1'b0);

assign icmp_ln86_1836_fu_486_p2 = (($signed(p_read10_int_reg) < $signed(18'd287)) ? 1'b1 : 1'b0);

assign icmp_ln86_1837_fu_492_p2 = (($signed(p_read9_int_reg) < $signed(18'd261759)) ? 1'b1 : 1'b0);

assign icmp_ln86_1838_fu_498_p2 = (($signed(p_read8_int_reg) < $signed(18'd261671)) ? 1'b1 : 1'b0);

assign icmp_ln86_1839_fu_504_p2 = (($signed(p_read10_int_reg) < $signed(18'd950)) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_324_p2 = (($signed(p_read11_int_reg) < $signed(18'd879)) ? 1'b1 : 1'b0);

assign or_ln117_1599_fu_698_p2 = (and_ln102_2034_fu_679_p2 | and_ln102_2019_reg_1496_pp0_iter1_reg);

assign or_ln117_1600_fu_613_p2 = (and_ln102_2024_fu_550_p2 | and_ln102_2019_reg_1496);

assign or_ln117_1601_fu_710_p2 = (or_ln117_1600_reg_1533 | and_ln102_2036_fu_688_p2);

assign or_ln117_1602_fu_734_p2 = (icmp_ln86_1810_reg_1328_pp0_iter1_reg | and_ln102_2037_fu_693_p2);

assign or_ln117_1603_fu_746_p2 = (icmp_ln86_1810_reg_1328_pp0_iter1_reg | and_ln102_2025_fu_670_p2);

assign or_ln117_1604_fu_828_p2 = (or_ln117_1603_reg_1575 | and_ln102_2039_fu_809_p2);

assign or_ln117_1605_fu_767_p2 = (icmp_ln86_1810_reg_1328_pp0_iter1_reg | and_ln102_2020_reg_1516);

assign or_ln117_1606_fu_840_p2 = (or_ln117_1605_reg_1585 | and_ln102_2040_fu_814_p2);

assign or_ln117_1607_fu_852_p2 = (or_ln117_1605_reg_1585 | and_ln102_2026_reg_1569);

assign or_ln117_1608_fu_864_p2 = (or_ln117_1607_fu_852_p2 | and_ln102_2042_fu_823_p2);

assign or_ln117_1609_fu_771_p2 = (icmp_ln86_1810_reg_1328_pp0_iter1_reg | and_ln104_reg_1505);

assign or_ln117_1610_fu_934_p2 = (or_ln117_1609_reg_1592_pp0_iter3_reg | and_ln102_2043_fu_915_p2);

assign or_ln117_1611_fu_897_p2 = (or_ln117_1609_reg_1592 | and_ln102_2027_fu_799_p2);

assign or_ln117_1612_fu_946_p2 = (or_ln117_1611_reg_1624 | and_ln102_2045_fu_924_p2);

assign or_ln117_1613_fu_958_p2 = (or_ln117_1609_reg_1592_pp0_iter3_reg | and_ln102_2021_reg_1602);

assign or_ln117_1614_fu_970_p2 = (or_ln117_1613_fu_958_p2 | and_ln102_2046_fu_929_p2);

assign or_ln117_1615_fu_984_p2 = (or_ln117_1613_fu_958_p2 | and_ln102_2028_fu_907_p2);

assign or_ln117_1616_fu_1044_p2 = (or_ln117_1615_reg_1636 | and_ln102_2048_fu_1025_p2);

assign or_ln117_1617_fu_1006_p2 = (or_ln117_1609_reg_1592_pp0_iter3_reg | and_ln102_reg_1544_pp0_iter3_reg);

assign or_ln117_1618_fu_1056_p2 = (or_ln117_1617_reg_1646 | and_ln102_2049_fu_1030_p2);

assign or_ln117_1619_fu_1068_p2 = (or_ln117_1617_reg_1646 | and_ln102_2029_reg_1630);

assign or_ln117_1620_fu_1080_p2 = (or_ln117_1619_fu_1068_p2 | and_ln102_2051_fu_1039_p2);

assign or_ln117_1621_fu_1094_p2 = (or_ln117_1617_reg_1646 | and_ln102_2022_reg_1556_pp0_iter4_reg);

assign or_ln117_1622_fu_1123_p2 = (or_ln117_1621_reg_1654 | and_ln102_2052_fu_1118_p2);

assign or_ln117_1623_fu_1128_p2 = (or_ln117_1621_reg_1654 | and_ln102_2030_fu_1114_p2);

assign or_ln117_1624_fu_1163_p2 = (or_ln117_1623_reg_1665 | and_ln102_2054_fu_1158_p2);

assign or_ln117_1625_fu_1311_p2 = (xor_ln104_reg_1539_pp0_iter7_reg | or_ln117_1609_reg_1592_pp0_iter7_reg);

assign or_ln117_fu_580_p2 = (and_ln102_2033_fu_565_p2 | and_ln102_2023_fu_541_p2);

assign select_ln117_1759_fu_594_p3 = ((or_ln117_fu_580_p2[0:0] == 1'b1) ? select_ln117_fu_586_p3 : 2'd3);

assign select_ln117_1760_fu_606_p3 = ((and_ln102_2019_reg_1496[0:0] == 1'b1) ? zext_ln117_187_fu_602_p1 : 3'd4);

assign select_ln117_1761_fu_703_p3 = ((or_ln117_1599_fu_698_p2[0:0] == 1'b1) ? select_ln117_1760_reg_1528 : 3'd5);

assign select_ln117_1762_fu_715_p3 = ((or_ln117_1600_reg_1533[0:0] == 1'b1) ? select_ln117_1761_fu_703_p3 : 3'd6);

assign select_ln117_1763_fu_722_p3 = ((or_ln117_1601_fu_710_p2[0:0] == 1'b1) ? select_ln117_1762_fu_715_p3 : 3'd7);

assign select_ln117_1764_fu_739_p3 = ((icmp_ln86_1810_reg_1328_pp0_iter1_reg[0:0] == 1'b1) ? zext_ln117_188_fu_730_p1 : 4'd8);

assign select_ln117_1765_fu_751_p3 = ((or_ln117_1602_fu_734_p2[0:0] == 1'b1) ? select_ln117_1764_fu_739_p3 : 4'd9);

assign select_ln117_1766_fu_759_p3 = ((or_ln117_1603_fu_746_p2[0:0] == 1'b1) ? select_ln117_1765_fu_751_p3 : 4'd10);

assign select_ln117_1767_fu_833_p3 = ((or_ln117_1604_fu_828_p2[0:0] == 1'b1) ? select_ln117_1766_reg_1580 : 4'd11);

assign select_ln117_1768_fu_845_p3 = ((or_ln117_1605_reg_1585[0:0] == 1'b1) ? select_ln117_1767_fu_833_p3 : 4'd12);

assign select_ln117_1769_fu_856_p3 = ((or_ln117_1606_fu_840_p2[0:0] == 1'b1) ? select_ln117_1768_fu_845_p3 : 4'd13);

assign select_ln117_1770_fu_870_p3 = ((or_ln117_1607_fu_852_p2[0:0] == 1'b1) ? select_ln117_1769_fu_856_p3 : 4'd14);

assign select_ln117_1771_fu_878_p3 = ((or_ln117_1608_fu_864_p2[0:0] == 1'b1) ? select_ln117_1770_fu_870_p3 : 4'd15);

assign select_ln117_1772_fu_890_p3 = ((or_ln117_1609_reg_1592[0:0] == 1'b1) ? zext_ln117_189_fu_886_p1 : 5'd16);

assign select_ln117_1773_fu_939_p3 = ((or_ln117_1610_fu_934_p2[0:0] == 1'b1) ? select_ln117_1772_reg_1619 : 5'd17);

assign select_ln117_1774_fu_951_p3 = ((or_ln117_1611_reg_1624[0:0] == 1'b1) ? select_ln117_1773_fu_939_p3 : 5'd18);

assign select_ln117_1775_fu_962_p3 = ((or_ln117_1612_fu_946_p2[0:0] == 1'b1) ? select_ln117_1774_fu_951_p3 : 5'd19);

assign select_ln117_1776_fu_976_p3 = ((or_ln117_1613_fu_958_p2[0:0] == 1'b1) ? select_ln117_1775_fu_962_p3 : 5'd20);

assign select_ln117_1777_fu_990_p3 = ((or_ln117_1614_fu_970_p2[0:0] == 1'b1) ? select_ln117_1776_fu_976_p3 : 5'd21);

assign select_ln117_1778_fu_998_p3 = ((or_ln117_1615_fu_984_p2[0:0] == 1'b1) ? select_ln117_1777_fu_990_p3 : 5'd22);

assign select_ln117_1779_fu_1049_p3 = ((or_ln117_1616_fu_1044_p2[0:0] == 1'b1) ? select_ln117_1778_reg_1641 : 5'd23);

assign select_ln117_1780_fu_1061_p3 = ((or_ln117_1617_reg_1646[0:0] == 1'b1) ? select_ln117_1779_fu_1049_p3 : 5'd24);

assign select_ln117_1781_fu_1072_p3 = ((or_ln117_1618_fu_1056_p2[0:0] == 1'b1) ? select_ln117_1780_fu_1061_p3 : 5'd25);

assign select_ln117_1782_fu_1086_p3 = ((or_ln117_1619_fu_1068_p2[0:0] == 1'b1) ? select_ln117_1781_fu_1072_p3 : 5'd26);

assign select_ln117_1783_fu_1098_p3 = ((or_ln117_1620_fu_1080_p2[0:0] == 1'b1) ? select_ln117_1782_fu_1086_p3 : 5'd27);

assign select_ln117_1784_fu_1106_p3 = ((or_ln117_1621_fu_1094_p2[0:0] == 1'b1) ? select_ln117_1783_fu_1098_p3 : 5'd28);

assign select_ln117_1785_fu_1133_p3 = ((or_ln117_1622_fu_1123_p2[0:0] == 1'b1) ? select_ln117_1784_reg_1660 : 5'd29);

assign select_ln117_1786_fu_1140_p3 = ((or_ln117_1623_fu_1128_p2[0:0] == 1'b1) ? select_ln117_1785_fu_1133_p3 : 5'd30);

assign select_ln117_fu_586_p3 = ((and_ln102_2023_fu_541_p2[0:0] == 1'b1) ? zext_ln117_fu_576_p1 : 2'd2);

assign tmp_fu_1175_p65 = 'bx;

assign tmp_fu_1175_p66 = ((or_ln117_1624_fu_1163_p2[0:0] == 1'b1) ? select_ln117_1786_reg_1670 : 5'd31);

assign xor_ln104_859_fu_516_p2 = (icmp_ln86_1810_reg_1328 ^ 1'd1);

assign xor_ln104_860_fu_628_p2 = (icmp_ln86_1811_reg_1339_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_861_fu_526_p2 = (icmp_ln86_1812_reg_1345 ^ 1'd1);

assign xor_ln104_862_fu_639_p2 = (icmp_ln86_1813_reg_1350_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_863_fu_779_p2 = (icmp_ln86_1814_reg_1356_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_864_fu_654_p2 = (icmp_ln86_1815_reg_1362_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_865_fu_545_p2 = (icmp_ln86_1816_reg_1368 ^ 1'd1);

assign xor_ln104_866_fu_665_p2 = (icmp_ln86_1817_reg_1374_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_867_fu_789_p2 = (icmp_ln86_1818_reg_1380_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_868_fu_794_p2 = (icmp_ln86_1819_reg_1386_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_869_fu_902_p2 = (icmp_ln86_1820_reg_1392_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_870_fu_1010_p2 = (icmp_ln86_1821_reg_1398_pp0_iter4_reg ^ 1'd1);

assign xor_ln104_871_fu_1015_p2 = (icmp_ln86_1822_reg_1404_pp0_iter4_reg ^ 1'd1);

assign xor_ln104_872_fu_1148_p2 = (icmp_ln86_1823_reg_1410_pp0_iter6_reg ^ 1'd1);

assign xor_ln104_fu_618_p2 = (icmp_ln86_reg_1322_pp0_iter1_reg ^ 1'd1);

assign xor_ln117_fu_570_p2 = (1'd1 ^ and_ln102_2031_fu_555_p2);

assign zext_ln117_187_fu_602_p1 = select_ln117_1759_fu_594_p3;

assign zext_ln117_188_fu_730_p1 = select_ln117_1763_fu_722_p3;

assign zext_ln117_189_fu_886_p1 = select_ln117_1771_fu_878_p3;

assign zext_ln117_fu_576_p1 = xor_ln117_fu_570_p2;

endmodule //conifer_jettag_accelerator_decision_function_112
