#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("x_0", 18, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("x_1", 18, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("x_2", 18, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("x_3", 18, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("x_4", 18, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("x_5", 18, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("x_6", 18, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("x_7", 18, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("x_8", 18, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("x_9", 18, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("x_10", 18, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("x_11", 18, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("x_12", 18, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("x_13", 18, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("x_14", 18, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("x_15", 18, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("score_0", 18, hls_out, 16, "ap_vld", "out_data", 1),
	Port_Property("score_0_ap_vld", 1, hls_out, 16, "ap_vld", "out_vld", 1),
	Port_Property("score_1", 18, hls_out, 17, "ap_vld", "out_data", 1),
	Port_Property("score_1_ap_vld", 1, hls_out, 17, "ap_vld", "out_vld", 1),
	Port_Property("score_2", 18, hls_out, 18, "ap_vld", "out_data", 1),
	Port_Property("score_2_ap_vld", 1, hls_out, 18, "ap_vld", "out_vld", 1),
	Port_Property("score_3", 18, hls_out, 19, "ap_vld", "out_data", 1),
	Port_Property("score_3_ap_vld", 1, hls_out, 19, "ap_vld", "out_vld", 1),
	Port_Property("score_4", 18, hls_out, 20, "ap_vld", "out_data", 1),
	Port_Property("score_4_ap_vld", 1, hls_out, 20, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "my_prj";
